export const utenti = [
  {
    id: 1,
    nome: "Luca",
    cognome: "Rossi",
    email: "luca.rossi@example.com",
    eta: 28,
    password: "12345",
  },
  {
    id: 2,
    nome: "Giulia",
    cognome: "Bianchi",
    email: "giulia.bianchi@example.com",
    eta: 34,
    password: "123d345",
  },
  {
    id: 3,
    nome: "Marco",
    cognome: "Verdi",
    email: "marco.verdi@example.com",
    eta: 25,
    password: "1234dd5",
  },
  {
    id: 4,
    nome: "Sara",
    cognome: "Neri",
    email: "sara.neri@example.com",
    eta: 30,
  },
  {
    id: 5,
    nome: "Alessandro",
    cognome: "Russo",
    email: "alessandro.russo@example.com",
    eta: 40,
  },
  {
    id: 6,
    nome: "Elena",
    cognome: "Gallo",
    email: "elena.gallo@example.com",
    eta: 22,
  },
  {
    id: 7,
    nome: "Davide",
    cognome: "Fontana",
    email: "davide.fontana@example.com",
    eta: 27,
  },
  {
    id: 8,
    nome: "Martina",
    cognome: "Colombo",
    email: "martina.colombo@example.com",
    eta: 33,
  },
  {
    id: 9,
    nome: "Francesco",
    cognome: "Ferrari",
    email: "francesco.ferrari@example.com",
    eta: 29,
  },
  {
    id: 10,
    nome: "Chiara",
    cognome: "Conti",
    email: "chiara.conti@example.com",
    eta: 31,
  },
  {
    id: 11,
    nome: "Andrea",
    cognome: "Marino",
    email: "andrea.marino@example.com",
    eta: 26,
  },
  {
    id: 12,
    nome: "Laura",
    cognome: "De Luca",
    email: "laura.deluca@example.com",
    eta: 35,
  },
  {
    id: 13,
    nome: "Stefano",
    cognome: "Romano",
    email: "stefano.romano@example.com",
    eta: 38,
  },
  {
    id: 14,
    nome: "Federica",
    cognome: "Costa",
    email: "federica.costa@example.com",
    eta: 24,
  },
  {
    id: 15,
    nome: "Giorgio",
    cognome: "Ricci",
    email: "giorgio.ricci@example.com",
    eta: 37,
  },
  {
    id: 16,
    nome: "Valentina",
    cognome: "Greco",
    email: "valentina.greco@example.com",
    eta: 32,
  },
  {
    id: 17,
    nome: "Matteo",
    cognome: "Lombardi",
    email: "matteo.lombardi@example.com",
    eta: 23,
  },
  {
    id: 18,
    nome: "Ilaria",
    cognome: "Moretti",
    email: "ilaria.moretti@example.com",
    eta: 36,
  },
  {
    id: 19,
    nome: "Simone",
    cognome: "Barbieri",
    email: "simone.barbieri@example.com",
    eta: 39,
  },
  {
    id: 20,
    nome: "Angela",
    cognome: "Giordano",
    email: "angela.giordano@example.com",
    eta: 41,
  },
];
